### ISSUE TITLE
Contents of `firmware_update_response` are overwritten before use in call to `handleFirmwareUpdate`

### ISSUE THREAD

**Issue by drpetersen** [Johboh/EspNowNetworkNode#1]
Hi @Johboh, first of all: thank you for your great EspNowNetwork framework! 

I have been using this for quite some time, and only recently got around to updating from EspNowNetwork 0.2.0 (or something like that) to the 0.8.2 versions of EspNowNetworkNode and EspNowNetworkHost (so far still doing my own device and firmware management). Now I can no longer do OTA updates, and got to the point where I think the root cause is that the content of `firmware_update_response` is overwritten between [its being set](https://github.com/Johboh/EspNowNetworkNode/blob/0a962886da3b6c9371aa2272e495c8bd35867727/src/impl/EspNowNode.cpp#L387) and [its actual use](https://github.com/Johboh/EspNowNetworkNode/blob/0a962886da3b6c9371aa2272e495c8bd35867727/src/impl/EspNowNode.cpp#L485) in `EspNowNode.cpp`.

In the call to `handleFirmwareUpdate`, the WiFi credentials (and everything else in `firmware_update_response`) are already overwritten with garbage, so the node cannot even connect to WiFi. I could fix this by replacing [this statement](https://github.com/Johboh/EspNowNetworkNode/blob/0a962886da3b6c9371aa2272e495c8bd35867727/src/impl/EspNowNode.cpp#L387) in `EspNowNode.cpp`:
```
          firmware_update_response = std::unique_ptr<EspNowChallengeFirmwareResponseV1>(
              reinterpret_cast<EspNowChallengeFirmwareResponseV1 *>(decrypted_data.data()));
```
with the following:
```
          firmware_update_response = 
              std::unique_ptr<EspNowChallengeFirmwareResponseV1>(new EspNowChallengeFirmwareResponseV1());
          std::memcpy(firmware_update_response.get(), response, sizeof(EspNowChallengeFirmwareResponseV1));
```

Probably there is a more elegant and efficient way to do this using the magic of `unique_ptr`s, which I am not too familiar with, as I have to admit … So, I'd be glad if you can take a look into this and either confirm (and adopt) this fix or else help me understand what I might be doing wrong here. Thank you!

**Comment by Johboh** [comment]
Great find @drpetersen! Just pure luck that it worked before. I have now fixed this is 0.8.3. However, I have not been able to test it as as all my stuff is packed away as I'm in the middle of a move, so please give it ago.
Also I hope upgrading from 0.2 to 0.8 goes well, as its quite the jump. You should be able to update all nodes one by one, but then you also must update the host after that (but only after).

**Comment by drpetersen** [comment]
Thank you very much @Johboh. Your new version 0.8.3 works for me.

Code-wise, the upgrade from 0.2 to 0.8 went rather smooth. Thanks for the hint on how to upgrade the network, I have yet to do that.

So far, I am still facing an issue with https upgrades; http works fine, but https won't so far (it did before). I will open a separate issue once I have narrowed it down some more.

For now, I wish you a smooth move and hope you settle in well in your new home.

**Comment by Johboh** [comment]
Thank you! 

Great! Will close this one.

I have not tested HTTPS, so it's only optimistically implemented. But I can look into this.
